services:
  resource:
    image: bencoronard/resource-rest-api:v1
    build:
      context: .
    ports:
      - 8081:8080
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_SERVER_PORT: 8080
      DEMO_SERVICE_ENVIRONMENT: dev
      DEMO_SERVICE_RESOURCE_REST_API_ID: RESOURCE_REST_API
      DEMO_SERVICE_RESOURCE_REST_API_SECRET_KEY: hireBenDemoSecretKey
      DEMO_DATABASE_POSTGRES_HOST: postgres
      DEMO_DATABASE_POSTGRES_PORT: 5432
      DEMO_DATABASE_POSTGRES_DB: hireben-db
      DEMO_DATABASE_POSTGRES_USER: hirebenDemoDbUser
      DEMO_DATABASE_POSTGRES_PASSWORD: hireBenDemoDbPassword
      APP_DATABASE_POOL_CONN_MAX: 5
      APP_DATABASE_POOL_CONN_MIN: 1
      

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - hireben_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hireben-db
      POSTGRES_USER: hirebenDemoDbUser
      POSTGRES_PASSWORD: hireBenDemoDbPassword
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "hirebenDemoDbUser"]
      interval: 5s
      retries: 3
      start_period: 5s

volumes:
  hireben_db_data: