services:
  app:
    image: gateway-scheduler:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - public
      - private
    environment:
      SERVER_PORT: 8080
      SERVER_API_KEY: loxbit888
      DATASOURCE_URI: jdbc:postgresql://db:5432/mdd
      DATASOURCE_USERNAME: loxbit
      DATASOURCE_PASSWORD: adminportal
      GATEWAY_URI: http://gateway:3000
      GATEWAY_API_KEY: loxley888

  gateway:
    image: api-gateway:latest
    ports:
      - 3000:8080
    restart: always
    networks:
      - public
    environment:
      SERVER_PORT: 8080
      SERVER_API_KEY: loxley888

  db:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    restart: always
    networks:
      - private
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/schema-postgresql.sql:/docker-entrypoint-initdb.d/schema-postgresql.sql
    environment:
      POSTGRES_DB: mdd
      POSTGRES_USER: loxbit
      POSTGRES_PASSWORD: adminportal

networks:
  public:
  private:

volumes:
  db_data:


  
