services:
  gatewayscheduler:
    image: lb-gateway-scheduler:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:9090
    depends_on:
      - db
      - gateway
    restart: always
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 1
    environment:
      APP_SERVICE_NAME: gateway-scheduler
      APP_SERVER_MODE: dev
      APP_SERVER_PORT: 9090
      APP_SERVER_TIMEOUT: 5
      APP_LOGGER_LOG_FILE_PATH: logs/gateway-scheduler.log
      APP_APP_VALIDATE_X_SECRET_KEY: loxbit888
      APP_DATABASE_POSTGRES_HOST: db
      APP_DATABASE_POSTGRES_PORT: 5432
      APP_DATABASE_POSTGRES_DBNAME: mdd
      APP_DATABASE_POSTGRES_USERNAME: loxbit
      APP_DATABASE_POSTGRES_PASSWORD: adminportal
      APP_CLIENTS_GATEWAY_URL_CSV: http://localhost:8001/open,http://localhost:8002/close
      APP_CLIENTS_GATEWAY_STAT_URL: https://dev-cdn.moneydd.co.th/app/app.json

  db:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    restart: always
    networks:
      - private
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/schema-postgresql.sql:/docker-entrypoint-initdb.d/schema-postgresql.sql
    environment:
      POSTGRES_DB: mdd
      POSTGRES_USER: loxbit
      POSTGRES_PASSWORD: adminportal

networks:
  private:

volumes:
  db_data:
