spring:
  application:
    name: "REST Task Scheduler"
  threads:
    virtual:
      enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/user"
    username: "user"
    password: ""
    driver-class-name: "org.postgresql.Driver"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "update"
    generate-ddl: true
    show-sql: true
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: "metadata"
            scripts:
              action: "create"
              create-target: "./src/main/resources/schema.sql"
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false

  sql:
    init:
      mode: "always"

  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "always"
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: "org.quartz.impl.jdbcjobstore.StdJDBCDelegate"
            dataSource: "quartz-data-source"
            tablePrefix: "QRTZ_"
            isClustered: false

quartz-data-Source:
  url: "jdbc:h2:file:./data/quartz_db;DB_CLOSE_ON_EXIT=false"
  driver-class-name: "org.h2.Driver"
  username: "sa"
  password: ""

---
# Development environment
spring:
  config:
    activate:
      on-profile: "dev"

  h2:
    console:
      enabled: true

logging:
  level:
    root: "WARN"
    "[org.springframework]": "INFO"
    "[org.springframework.security]": "DEBUG"

server:
  port: ${SERVER_PORT:3000}

api:
  internal:
    secret:
      key: "api-key-for-this-service"
  external:
    gateway:
      uri: "http://localhost:7777"
      secret:
        key: "api-key-for-gateway-service"
    audit:
      uri: "http://localhost:8888"
      secret:
        key: "api-key-for-audit-service"