spring:
  application:
    name: "REST Task Scheduler"
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "always"

---
# Development environment
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: "jdbc:postgresql://localhost:5432/user"
    driver-class-name: "org.postgresql.Driver"
    username: "user"
    password: ""

logging:
  level:
    root: "WARN"
    "[org.springframework]": "INFO"
    "[org.springframework.security]": "DEBUG"

server:
  port: ${SERVER_PORT:3000}

api:
  internal:
    secret:
      key: "api-key-for-this-service"
  external:
    gateway:
      uri: "http://localhost:7777"
      secret:
        key: "api-key-for-gateway-service"
    audit:
      uri: "http://localhost:8888"
      secret:
        key: "api-key-for-audit-service"
---
# Production environment