spring:
  application:
    name: "REST Task Scheduler"
  threads:
    virtual:
      enabled: true

  datasource:
    postgresql:
      url: "jdbc:postgresql://localhost:5432/user"
      driver-class-name: "org.postgresql.Driver"
      username: "user"
      password: ""
    h2:
      url: "jdbc:h2:file:./data/localDb"
      driver-class-name: "org.h2.Driver"
      username: "sa"
      password: ""

  sql:
    init:
      mode: "always"
      platform: "postgresql, h2"
      schema-locations: "classpath:db/migration/schema-postgresql.sql, optional:classpath:db/migration/schema-h2.sql"
      data-locations: "optional:classpath:db/migration/data-postgresql.sql, optional:classpath:db/migration/data-h2.sql"

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: "update"
    
  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "never"
    properties:
      "[org.quartz.jobStore.tablePrefix]": "admin_portal.QRTZ_"
      "[org.quartz.jobStore.driverDelegateClass]": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"

---
# Development environment
spring:
  config:
    activate:
      on-profile: "dev"

  h2:
    console:
      enabled: true

logging:
  level:
    root: "WARN"
    "[org.springframework]": "INFO"
    "[org.springframework.security]": "DEBUG"

server:
  port: ${SERVER_PORT:3000}

api:
  internal:
    secret:
      key: "api-key-for-this-service"
  external:
    gateway:
      uri: "http://localhost:7777"
      secret:
        key: "api-key-for-gateway-service"
