spring:
  application:
    name: "REST Task Scheduler"
  threads:
    virtual:
      enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:5432/user"
    driver-class-name: "org.postgresql.Driver"
    username: "user"
    password: ""

  sql:
    init:
      mode: "always"
      platform: "postgresql"
      schema-locations: "classpath:db/migration/schema-postgresql.sql"
      data-locations: "optional:classpath:db/migration/data-postgresql.sql"

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: "update"
    
  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "never"
    properties:
      "[org.quartz.jobStore.tablePrefix]": "admin_portal.QRTZ_"
      "[org.quartz.jobStore.driverDelegateClass]": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"

server:
  port: ${SERVER_PORT:8080}

api:
  internal:
    secret:
      key: "loxbit888"
      
  external:
    gateway:
      uri: "http://localhost:7777"
      secret:
        key: "loxley888"

logging:
  level:
    root: "WARN"
    "[org.springframework]": "INFO"
    "[org.springframework.security]": "DEBUG"

app:
  environment: "dev"

---
# Development environment
# spring:
#   config:
#     activate:
#       on-profile: "dev"


