spring:
  application:
    name: "API Gateway Demo"
  threads:
    virtual:
      enabled: true

server:
  port: "${SERVER_PORT:7786}"

api:
  internal:
    secret:
      key: "${SERVER_API_KEY:mdd1234}"
