spring:
  application:
    name: "API Gateway Demo"
  threads:
    virtual:
      enabled: true

logging:
  level:
    "[org.springframework]": "INFO"
    "[org.springframework.security]": "DEBUG"

server:
  port: ${SERVER_PORT:8080}

api:
  internal:
    secret:
      key: "loxley888"
